version: "3.7"
services:
  frontend:
    build:
      context: chatapp-frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./chatapp-frontend/src:/docker-chatapp-frontend/src
      - /project/node_modules
    environment:
       - CHOKIDAR_USEPOLLING=true
       - WATCHPACK_POLLING=true
